[phases.build]
cmds = [
    'npm ci',
    'npm run build',
    'composer install --no-dev --optimize-autoloader',
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache'
] 